#server:
 #port: 9090

#eureka:
 #server:
 #   enable-self-preservation: false
# client:
   #registerWithEureka: false
   #serviceUrl:
     # defaultZone: http://localhost:9090/eureka/
      
      
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
      