spring:
  application:
    name: config-server
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sidd-harth/config-server
        #native:
          #search-locations: classpath:/common-folder  
       
server:
  port: 8888
  
